### ISSUE TITLE
Remove prefixes in shader headers

### ISSUE THREAD

**Issue by deep-programmer** [Forceflow/opengl_viewer#1]
In the `shader_tools` sub-directory, please remove:
- for `GLSLShader.h`, the `GLSLShader::` prefixes to methods
- for `GLSLProgram.h`, the `GLSLProgram::` prefixes to methods

**Comment by Forceflow** [comment]
Fixed in 67a87c9d4c72cdae4c442d3f4e4cdbf7dbed4234
